//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmasi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Farmasi.Resources.Translator", typeof(Translator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის შესახებ.
        /// </summary>
        public static string AboutProduct {
            get {
                return ResourceManager.GetString("AboutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამატება.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამატებითი.
        /// </summary>
        public static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მისამართი.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კალათაში დამატება.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ყველა ველი აუცილებელია!.
        /// </summary>
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ყველა * ველის შევსება აუცილებელია!.
        /// </summary>
        public static string AllStarFieldsRequired {
            get {
                return ResourceManager.GetString("AllStarFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თანხა.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორიზაცია.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბონუსები.
        /// </summary>
        public static string Bonuses {
            get {
                return ResourceManager.GetString("Bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კალათა.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კატალოგი.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცვლა.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლის შეცვლა.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აირჩიე ენა.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კოდი.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფერები.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვალუტა.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარე პაროლი.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარე პაროლი ემთხვევა ახალს!.
        /// </summary>
        public static string CurrentPasswordAndNewPasswordAreTheSame {
            get {
                return ResourceManager.GetString("CurrentPasswordAndNewPasswordAreTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარე პაროლი არასწორია!.
        /// </summary>
        public static string CurrentPasswordIsNotValid {
            get {
                return ResourceManager.GetString("CurrentPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თარიღი.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დავალიანება.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ-ფოსტა.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ-ფოსტა არ ეკუთვნის მითითებულ მომხმარებელს!.
        /// </summary>
        public static string EmailNotValidForThisUser {
            get {
                return ResourceManager.GetString("EmailNotValidForThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა პაროლის აღდგენისას!.
        /// </summary>
        public static string ErrorOnRecovery {
            get {
                return ResourceManager.GetString("ErrorOnRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა შენახვისას!.
        /// </summary>
        public static string ErrorOnSave {
            get {
                return ResourceManager.GetString("ErrorOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფარმასი.
        /// </summary>
        public static string Farmasi {
            get {
                return ResourceManager.GetString("Farmasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი, გვარი.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გენერაცია.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჯგუფიდან მიღებული სარგებელი.
        /// </summary>
        public static string GroupBonus {
            get {
                return ResourceManager.GetString("GroupBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჯგუფის შესყიდვა დღგ-ს გარეშე.
        /// </summary>
        public static string GroupBonusWithoutVat {
            get {
                return ResourceManager.GetString("GroupBonusWithoutVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჯგუფის შესყიდვა დღგ-ს ჩათვლით.
        /// </summary>
        public static string GroupBonusWithVat {
            get {
                return ResourceManager.GetString("GroupBonusWithVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სურათი.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქართულად.
        /// </summary>
        public static string InGeorgian {
            get {
                return ResourceManager.GetString("InGeorgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ლინკი.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გასვლა.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავარი.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ახალი პაროლი.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ახალი პაროლი გამოგზავნილია თქვენს ელ-ფოსტაზე!.
        /// </summary>
        public static string NewPasswordSentOnYourEmail {
            get {
                return ResourceManager.GetString("NewPasswordSentOnYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნომერი.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეკვეთა.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროცენტი.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი.
        /// </summary>
        public static string PersonalCode {
            get {
                return ResourceManager.GetString("PersonalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ს/კ.
        /// </summary>
        public static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პ/ნ.
        /// </summary>
        public static string PN {
            get {
                return ResourceManager.GetString("PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფასი.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ძირითადი.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი სარგებელი.
        /// </summary>
        public static string PrivateBonus {
            get {
                return ResourceManager.GetString("PrivateBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი შესყიდვა.
        /// </summary>
        public static string PrivateSales {
            get {
                return ResourceManager.GetString("PrivateSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის კოდი.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის დეტალები.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის დასახელება.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროფილი.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შინაარსი.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რაოდენობა.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აღდგენა.
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლის აღდგენა.
        /// </summary>
        public static string RecoveryPassword {
            get {
                return ResourceManager.GetString("RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to განახლება.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რეგისტრაცია.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ამოშლა.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაიმეორეთ პაროლი.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to განმეორებითი პაროლი არ ემთხვევა ახალს!.
        /// </summary>
        public static string RepeatPasswordAndNewPasswordAreNotTheSame {
            get {
                return ResourceManager.GetString("RepeatPasswordAndNewPasswordAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to განმეორებითი პაროლი არ ემთხვევა წინას!.
        /// </summary>
        public static string RepeatPasswordAndPasswordAreNotTheSame {
            get {
                return ResourceManager.GetString("RepeatPasswordAndPasswordAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნაშთი.
        /// </summary>
        public static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF მომხმარებელი არ არსებობს!.
        /// </summary>
        public static string RfUserDoesNotExists {
            get {
                return ResourceManager.GetString("RfUserDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაყიდვები.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ძებნა.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შესვლა.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თანამშრომლები.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სტრუქტურა.
        /// </summary>
        public static string Structure {
            get {
                return ResourceManager.GetString("Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი მსგავსი მომხმარებლის სახელით უკვე არსებობს!.
        /// </summary>
        public static string UserGivenUserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserGivenUserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი და პაროლი აუცილებელია!.
        /// </summary>
        public static string UserNameAndPasswordRequired {
            get {
                return ResourceManager.GetString("UserNameAndPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხ. სახელი.
        /// </summary>
        public static string UsrName {
            get {
                return ResourceManager.GetString("UsrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი ან პაროლი არასწორია!.
        /// </summary>
        public static string WrongUserNameOrPassword {
            get {
                return ResourceManager.GetString("WrongUserNameOrPassword", resourceCulture);
            }
        }
    }
}
